create table NHANVIEN(
	MANV VARCHAR(7) PRIMARY KEY,
    HOTENNV VARCHAR(40),
    NGAYSINH DATE,
    GIOITINH VARCHAR(4),
    MACHUCVU VARCHAR(4)
);

create table DUAN(
	MADUAN VARCHAR(7) PRIMARY KEY,
    TENDUAN VARCHAR(100),
    KINHPHI INT,
    TGBD DATE,
    TGKT DATE
);

create table CHUCVU(
	MACHUCVU VARCHAR(4) PRIMARY KEY,
    TENCHUCVU VARCHAR(40),
    LUONGCB INT
);

ALTER TABLE NHANVIEN
ADD FOREIGN KEY(MACHUCVU) 
REFERENCES CHUCVU(MACHUCVU)
ON DELETE SET NULL;

create table PHANCONG(
	MADUAN VARCHAR(7),
    MANV VARCHAR(7),
    SONGAYCONG INT,
    PRIMARY KEY(MADUAN, MANV),
    FOREIGN KEY (MADUAN) REFERENCES DUAN(MADUAN) ON DELETE CASCADE,
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE CASCADE
);